name: Format Dart Code

on:
  push:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write # لإعطاء صلاحية الكتابة والـ commit
    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1

      - name: Format Dart files
        run: dart format .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: auto-format Dart code"
